### ISSUE TITLE
Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by Macilias** [scriptex/react-accordion-ts#279]
Tried to use the component within a typescript react native environment and got the following exception:

error: (CLIENT) Invariant Violation: Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

**Comment by scriptex** [comment]
Hi and thanks for reporting this. I am almost 100% sure that this package won't work in a React Native environment. It is intended to be used in a browser environment only.
I am going to need to setup a React Native project to test it.

**Comment by scriptex** [comment]
@Macilias can you also paste some example code so I can easily reproduce your issue?

**Comment by scriptex** [comment]
Hi @Macilias, I currently don't have the time to implement this for React Native.
Meanwhile, you can try and find another package. I am pretty sure there are a lot of possibilities out there :). Also, feel free to open and PR if you want this implemented soon.
