### ISSUE TITLE
React should not be specified under "dependencies" in package.json

### ISSUE THREAD

**Issue by jaydenkieran** [scriptex/react-accordion-ts#388]
Hi there,

I'm having troubles using this library in a project that was bootstrapped with `create-react-app`. When running the project while utilizing this library, I receive this error:

> Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

I believe that the issue is being caused by reason 3 that is listed above - more than one copy of React in the same app. This, I suspect, is because this library incorrectly includes React as a dependency inside `package.json` rather than just simply a peer dependency. Relevant lines:

https://github.com/scriptex/react-accordion-ts/blob/f3dd498f3a75fa445ed7811af111394f2656c8bf/package.json#L29-L32

I also suspect that there may be a version mismatch, but regardless, listing React as a dependency in a library with reusable components is a big no and can cause severe problems such as the one above because of multiple React instances being installed.

Edit: For complete clarity, React and react-dom should be specified only in `peerDependencies` (for the consumers of the library) and `devDependencies` (for when you're developing the library)

Please also use `"react": "^16.8.0"` rather than specifying `17.0.1` as the only version that the library works on, unless that is actually true and it only works on 17.0.1 (same logic for react-dom too)

**Comment by scriptex** [comment]
Hi @jaydenkieran,
thank you for the heads-up.

I will try to fix this ASAP. In the mean time, I am always more than happy to receive pull requests, so if you feel you can fix this fast , feel free to open one.

I will try to find some time during the next week.
