### ISSUE TITLE
Add props for open items

### ISSUE THREAD

**Issue by vaneatka** [scriptex/react-accordion-ts#496]
Is there possibility to add (or maybe it exists) to check which of items is open or not?

export interface AccordionProps {
	items: ReadonlyArray<AccordionItem>;
	duration: number;
	multiple: boolean;
}
may contain an another active prop for an array of open props (by indexes).

**Comment by scriptex** [comment]
@vaneatka if I understand this correctly, you would like to specify which items are open initially, right? 
If yes, please check if the [linked PR](https://github.com/scriptex/react-accordion-ts/pull/497) works for you.

**Comment by scriptex** [comment]
@vaneatka this has been released and is available to download from NPM and Github.
For more info please see the [release notes](https://github.com/scriptex/react-accordion-ts/releases/tag/1.2.0)
Thank you for your contribution. 🎉

**Comment by vaneatka** [comment]
@scriptex thank you, basically the main purpose of my question was, to have a possibility to check which item is open...
 To be able to switch the \/ (down) caret to /\ (up). In order to show open/close possibility.

**Comment by scriptex** [comment]
@vaneatka you could have done this by using the `aria-expanded` attribute in your CSS. If you are looking for an alternative solution, please show me your use case and I will try to help 🙂
